substitutions:
  device_name: x10-receiver
  friendly_name: 'X10 Receiver'

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

esp8266:
  board: d1_mini
  framework:
    version: recommended

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome_api_key

# Allow Over-The-Air updates
ota:
  - platform: esphome
    password: !secret esphome_ota_key

wifi:
  min_auth_mode: WPA2
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} fallback hotspot"
    password: !secret hotspot_password

# Allow provisioning Wi-Fi via serial or web_server
#improv_serial:
# or connect to the fallback ap and get redirected to a web page for wifi credentials
# To have a "next url" for improv serial
web_server:

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

external_components:
  source: github://DonKracho/ESPHome-component-X10-Receiver/components[@main]
  #source: D:\ESPHome-component-X10-Receiver\components
  refresh: 0s
  components: [rf_scanner]

time:
  # used for creating timesamps in text sensors
  - platform: homeassistant
    id: homeassistant_time

rf_scanner:
  id: my_scanner
  sensor_type: "DIGITAINER"  # use "DIGITAINER" or "NEC" (or "DRY-TEST" for dummy data injection) 
  data_pin: D7    # GPIO13 pin where the 433MHZ receiver data output is connected to
  led_pin: D4     # GPIO2 optional for scanning feedback via onboard LED

text_sensor:
  - platform: rf_scanner
    name: 'Remote'
    rf_scanner: my_scanner
    id: remote
    channel:
      name: "Channel"
      id: channel
    command:
      name: "Command"
      id: command
    command_name:
      name: "Command Name"
      id: command_name
    device_pad:
      name: "Device Pad"
      id: device_pad
    motion_pad:
      name: "Motion Pad"
      id: motion_pad
    number_pad:
      name: "Number Pad"
      id: number_pad
